[tool.poetry]
name = "trace-gen"
version = "0.1.0"
description = ""
authors = ["Donghyun Kim <donghyun@utexas.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
